name: Publish Home Assistant Docker images

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: taylanselvi
          password: AVnPwE3={RHG)Q*>2d;96^JCo8>866
      - name: Publish
        uses: home-assistant/builder@master
        with:
          args: |
            --all \
            --target hello-a2i2 \
            --docker-hub taylanselvi \
            --image hello-a2i2
